# Generated by Django 5.1.3 on 2024-11-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=100)),
                ('brand_category_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketcars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_year', models.PositiveIntegerField()),
                ('car_mileage', models.PositiveIntegerField()),
                ('car_color', models.CharField(max_length=30)),
                ('car_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_have', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('brand_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketcars.brand')),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketcars.carmodel')),
            ],
        ),
    ]
